export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login'
export const RECOMENDATION_ROUTE = '/recomendation'
export const OPROS_FIRST_ROUTE = '/opros/1'
export const OPROS_SECOND_ROUTE = '/opros/2'
export const OPROS_THIRD_ROUTE = '/opros/3'
export const TEST_EVENT = '/test_event'
